# This is a basic workflow to help you get started with Actions

name: Add Reviewers Job 

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, reopened, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  addreviewers:
    uses: liujinye-sys/public-actions/.github/workflows/add-reviewers.yml@trunk
    secrets: inherit
